zuul:
    prefix : /api
    routes:
        flights:
          path: /flights/**
          serviceId: FLIGHT-SERVICE
          stripPrefix: false

ribbon:
  eureka:
    enabled: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
